First simple attempt registration
Exzellenz-Coin/exzellenz-coin-frontend pull request #2
Opened 2021-09-12 22:52 UTC by shnubu

Open for any critics i am frontend noob, log in is not realized yet

2021-09-12 22:58 UTC, Hialus requested changes
The .idea Folder and .iml files should be placed in the .gitignore file as well.

2021-09-12 22:58 UTC, Hialus commented on .eslintcache
> +[{"C:\\Users\\alexa\\WebstormProjects\\exzellenz-coin-frontend\\src\\index.tsx":"1","C:\\Users\\alexa\\WebstormProjects\\exzellenz-coin-frontend\\src\\App.tsx":"2","C:\\Users\\alexa\\WebstormProjects
Ich bin kein Experte was React angeht, aber da diese Datei cache im Namen hat würde ich sagen, dass diese Datei zur .gitignore Datei hinzugefügt werden.

2021-09-12 23:20 UTC, Hialus approved these changes

2021-09-12 23:21 UTC, Hialus commented
From my side everything looks good. But it would be great if someone with more React experience could take a look as well.

2021-09-13 11:21 UTC, MarcZiegler commented
Looks good to me!

2021-09-13 11:21 UTC, merged